name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  unit-and-integration:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Run integration tests
        run: npm run test:integration
      
      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/
          retention-days: 5

  e2e-android:
    name: E2E Tests (Android)
    runs-on: macos-latest
    needs: unit-and-integration
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Detox CLI
        run: npm install -g detox-cli
      
      - name: Install Appium
        run: npm install -g appium
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Install Android Emulator
        run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-30;google_apis;x86_64"
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_4_API_30 -k "system-images;android-30;google_apis;x86_64" -d "pixel_4"
      
      - name: Build app for detox
        run: npm run e2e:build:android
      
      - name: Run Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd Pixel_4_API_30 -no-audio -no-window -no-snapshot -gpu swiftshader_indirect &
          android-wait-for-emulator
      
      - name: Run E2E tests
        run: npm run e2e:test:android

  e2e-ios:
    name: E2E Tests (iOS)
    runs-on: macos-latest
    needs: unit-and-integration
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Detox CLI
        run: npm install -g detox-cli
      
      - name: Install iOS dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
          gem install xcpretty
      
      - name: Cache CocoaPods dependencies
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      
      - name: Install CocoaPods
        run: |
          cd ios
          pod install
      
      - name: Build app for detox
        run: npm run e2e:build:ios
      
      - name: Run E2E tests
        run: npm run e2e:test:ios